name: Build Plugin ZIP on Publishing Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set plugin slug
        run: echo "PLUGIN_SLUG=insert-codes" >> $GITHUB_ENV

      - name: Build plugin
        run: |
          mkdir build
          rsync -av --exclude-from=.distignore ./ build/${{ env.PLUGIN_SLUG }}

      - name: Create ZIP
        run: |
          cd build
          zip -r ${{ env.PLUGIN_SLUG }}.zip ${{ env.PLUGIN_SLUG }}

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/${{ env.PLUGIN_SLUG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
